openapi: 3.1.0
info:
  title: Template web service
  description: This is a template of a web service
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/template-python/blob/main/LICENSE
  version: 0.0.0
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /:
    get:
      summary: Read Root
      operationId: read_root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /predict:
    get:
      summary: Predict using LSTM-BNN
      operationId: predict_predict_get
      responses:
        '200':
          description: Prediction result
          content:
            application/json:
              schema: {}
